name: Deploy Backend to AWS ECS

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY_BACKEND: 091295763720.dkr.ecr.ap-south-1.amazonaws.com/ctf-backend:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_BACKEND

      # Build, tag, and push backend
      - name: Build and push backend Docker image
        run: |
          docker build -t $ECR_REPOSITORY_BACKEND:latest ./backend
          docker push $ECR_REPOSITORY_BACKEND:latest

      # Update ECS Service to use new image (backend)
      - name: Deploy to ECS Backend
        run: |
          aws ecs update-service \
            --cluster ctf-cluster \
            --service ctf-backend-service \
            --force-new-deployment
